#!/bin/bash
. uevent-sh-functions

# Создаем событие добавления смарт-карты
# Событие -- это файл хранящий описание события через переменные
event="$(make_event)"
echo "SMARTCARD_CONNECTED=1" >> "$event"
release_event hello-smartcard "$event"
